--  Vytvoření MV 
CREATE MATERIALIZED VIEW XSTEFLM00.PREPRAVA_SUROVIN_MV
  BUILD IMMEDIATE
  REFRESH COMPLETE ON DEMAND
AS
SELECT
  p.TYP_SUROVINY,
  p.STAV,
  COUNT(*)        AS POCET_PREPRAV,
  SUM(p.MNOŽSTVÍ) AS CELKOVE_MNOZSTVI
FROM XDOLEZF00.PŘEPRAVA p
JOIN XDOLEZF00.SUROVINA   s
  ON p.TYP_SUROVINY = s.TYP_SUROVINY
GROUP BY p.TYP_SUROVINY, p.STAV
ORDER BY p.TYP_SUROVINY, p.STAV
;

-- První kontrolní SELECT 
SELECT *
  FROM XSTEFLM00.PREPRAVA_SUROVIN_MV
ORDER BY TYP_SUROVINY, STAV
;

-- Vložení testovacího řádku do zdrojové tabulky
INSERT INTO XDOLEZF00.PŘEPRAVA (
  ID_PŘEPRAVY, CENA, DATUM_ZADÁNÍ, STAV,
  TYP_SUROVINY, MNOŽSTVÍ, ČÍSLO_LICENCE, ID_SKLADU_Z, ID_SKLADU_DO
) VALUES (
  XSTEFLM00.seq_preprava_id.NEXTVAL,
  555, SYSDATE, 'TEST-COMPLETE', 'Železo', 321, 2, 2, 3
);
COMMIT;

-- SELECT před obnovou – změna se dosud nepromítla
SELECT *
  FROM XSTEFLM00.PREPRAVA_SUROVIN_MV
 WHERE STAV = 'TEST-COMPLETE'
;

-- Spuštění COMPLETE refresh

CALL DBMS_MVIEW.REFRESH('XSTEFLM00.PREPRAVA_SUROVIN_MV');


-- SELECT po obnově – nová data už jsou zahrnuta
SELECT *
  FROM XSTEFLM00.PREPRAVA_SUROVIN_MV
 WHERE STAV = 'TEST-COMPLETE'
;

-- Kontrola metadat – typ a datum posledního refresh
SELECT
  MVIEW_NAME,
  LAST_REFRESH_TYPE,
  LAST_REFRESH_DATE
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'PREPRAVA_SUROVIN_MV'
;

DROP TABLE XSTEFLM00.DUL CASCADE CONSTRAINTS;
DROP TABLE XSTEFLM00.FIRMA CASCADE CONSTRAINTS;
DROP TABLE XSTEFLM00.JE_SOUČÁSTÍ CASCADE CONSTRAINTS;
DROP TABLE XSTEFLM00.KONTRAKT CASCADE CONSTRAINTS;
DROP TABLE XSTEFLM00.OSOBA CASCADE CONSTRAINTS;
DROP TABLE XSTEFLM00.PŘEPRAVA CASCADE CONSTRAINTS;
DROP TABLE XSTEFLM00.SKLAD CASCADE CONSTRAINTS;
DROP TABLE XSTEFLM00.SUROVINA CASCADE CONSTRAINTS;
DROP TABLE XSTEFLM00.VLASTNÍ CASCADE CONSTRAINTS;
DROP SEQUENCE XSTEFLM00.SEQ_DUL_ID;
DROP SEQUENCE XSTEFLM00.SEQ_FIRMA_LICENCE;
DROP SEQUENCE XSTEFLM00.SEQ_KONTRAKT_CISLO;
DROP SEQUENCE XSTEFLM00.SEQ_OSOBA_ID;
DROP SEQUENCE XSTEFLM00.SEQ_PREPRAVA_ID;
DROP SEQUENCE XSTEFLM00.SEQ_SKLAD_ID;